Feat/13
codeinthedarkbrasil/manage-citd pull request #41
Opened 2023-07-16 01:23 UTC by gabepinheiro

2023-07-16 19:28 UTC, vinibispo approved these changes
LGTM 🚀 🤩

2023-07-17 21:56 UTC, fdaciuk requested changes
That's great @gabepinheiro! 
Just made a few comments, really easy fixes. Thanks a lot ❤️

2023-07-17 21:56 UTC, fdaciuk commented on src/app/api/events/[event]/participants/register-participants/route.ts
> +  const existParticipant = await prisma.user.findFirst({
I should put the `email` as an unique field. Forgot about that. I'll fix it, then you don't need to check try to find the user before creating.

2023-07-17 21:56 UTC, fdaciuk commented on src/app/api/events/[event]/participants/register-participants/route.ts
> +      { status: 400 },
I guess `422` is a better status code here.

2023-07-17 21:56 UTC, fdaciuk commented on src/app/api/events/[event]/participants/register-participants/route.ts
> +    status: 200,
`200` is the default status code, we don't need it here.

2023-07-17 21:56 UTC, fdaciuk commented on src/app/events/[event]/page.tsx
> +    registerParticipantMutation.mutateAsync({ data, event })
You're not handling the error here, so you can just use `mutate` instead of `mutateAsync`.

2023-07-17 21:56 UTC, fdaciuk commented on src/app/events/[event]/participants/data-participants.ts
> +    `/api/events/${event}/participants/register-participants`,
Since you're registering one participant at a time, the route should be named as `register-participant`, singular.

2023-07-17 21:56 UTC, fdaciuk commented on src/components/register-participant-modal/modal.tsx
> +const formSchema = z.object({
This schema should be in `./src/shared/types/participants.ts`, and the type `RegisterParticipant` should be infered from that and exported.

2023-07-18 22:03 UTC, fdaciuk requested changes

2023-07-18 22:03 UTC, fdaciuk commented on src/app/events/[event]/participants/data-participants.ts
> +interface RegisterParticipantInput {
Use `type` instead of `interface`

2023-07-18 22:03 UTC, fdaciuk commented on src/app/events/[event]/participants/data-participants.ts
> +    return Promise.reject(message)
Please add a `// TODO` comment to handle this error in the future

2023-07-18 22:27 UTC, fdaciuk approved these changes
Thanks @gabepinheiro! LGTM ❤️ 💃🏾 ✨

2023-07-18 22:28 UTC, merged